name: Build Badwords YAML

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        persist-credentials: false  # Disable the default token

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      working-directory: minecraft
      run: npm install

    - name: Run build script
      working-directory: minecraft
      run: npm run build

    - name: Commit and push changes
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add minecraft/BadWords.yml
        if git diff --cached --quiet; then
          echo "No changes to commit."
          exit 0
        fi
        git commit -m "Auto-update BadWords.yml"
        git push https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
